version: '3.1'
services:
  web:
    build: .
    ports:
     - "1280:1280"
    links:
     - "db:database"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=#db@cbb48
     - MYSQL_PASSWORD=cbb48
     - MYSQL_USER=appuser
     - MYSQL_DATABASE=SkatFellows
    volumes:
     - /var/database